### ISSUE TITLE
Set up your Kanban Board

### ISSUE THREAD

**Issue by enionsouza** [aristides1000/awesome-events-back-end#29]
In this project, we created [this Github Kanban Board](https://github.com/aristides1000/marketplace-back-end/projects/1)
We have **three participants** for this project: 
- @aristides1000
- @DanSam5K
- @enionsouza

[Screenshot](https://drive.google.com/file/d/18aXSDKtvEIL8556Z8LIoQhxTxAZCe57c/view?usp=sharing)

**Comment by rvvergara** [comment]
Hi team, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

While your story points are well balanced per team member:

@aristides1000 = 60
@DanSam5K = 60
@enionsouza = 60

I observe that a lot of the tasks have multiple assignees. I am very much in favor of collaboration. However, having too many tasks that require multiple team members might mean those tasks are too big. 

In relation to this, I observe that a lot of the tasks have 8pts above. In practice, when we estimate user stories and use the modified-Fibonacci, 8pts normally means you do a task for 2 weeks (corresponding to a 2-week sprint). Therefore, tasks that are at least 8pts might be too big to be called a single user story. I do recommend you further break it down into smaller chunks (max size for a task ideally should be just 5 pts). 

You can use my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make better software engineers.

Cheers!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by aristides1000** [comment]
- Thank you @rvvergara, for your feedback regarding our Kanban Board Project, all issues have been addressed as suggested. 👍

**Comment by rvvergara** [comment]
Hi team, 

In my opinion, your project is ready to be coded!  There is nothing else to say other than... it's time to merge it :shipit: 

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by DanSam5K** [comment]
- Thank you @rvvergara for your amazing feedback.
